### ISSUE TITLE
Alpha2 devlist

### ISSUE THREAD

**Issue by CaerCam** [wpmovielibrary/wpmovielibrary#326]
This is a list of developments shipped for version 3.0-alpha2. This alpha will focus on porting version 2.x front-end features to the 3.0 code.
### Templates
- [x] #327 Enhance the Template class
### ShortCodes
- [x] #328 Build an extensible ShortCode class
- [x] #329 Port version 2.x ShortCodes
- [x] #330 Unify and simplify ShortCodes options
### Widgets
- [x] #336 Port version 2.x Widgets
### Permalinks
- [x] #334 Implement basic permalinks translation
- [x] #335 Implement custom permalinks structures support
### Grids
- [x] #331 Port version 2.1.5 JavaScript-powered grid
- [x] #332 Implement basic JS-disabled support for the grid
- [x] #333 Implement taxonomy grids
